version: '2'
services:
  redis:
    image: redis
    networks:
      - backend
  notifier:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DOCKER_REDIS_HOST: "redis"
      PUSHBULLET_API_KEY: "${PUSHBULLET_API_KEY}"
    volumes:
      - .:/myapp
    depends_on:
      - redis
    networks:
      - backend
networks:
  backend:
    driver: bridge