version: '2'
services:
  redis:
    image: redis
    networks:
      - backend
  notifier:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DOCKER_REDIS_HOST: "redis"
      PUSHBULLET_API_KEY: "${PUSHBULLET_API_KEY}"
    # volumes:
    #   - .:/myapp
    depends_on:
      - redis
    networks:
      - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - frontend
  haproxy:
    build:
      context: .
      dockerfile: ./Dockerfile.haproxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - notifier
    networks:
      - backend
      - frontend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge